package com.yukista.tutaua.box;
import android.app.*;import android.content.pm.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.text.*;import java.util.*;

public final class UpdatesActivity extends Activity{
 private static final int BG=Color.rgb(7,10,18),SURFACE=Color.rgb(22,28,42),MUTED=Color.rgb(156,166,190);private static final String[][] APPS={{"com.yukista.tutaua.box","Tutaua Box"},{"tv.tutaua.app","Futbol"},{"com.yukista.tutaua","Sèries i pel·lícules"},{"com.yukista.tutaua.games","Jocs"},{"com.yukista.tutaua.tdt","TDT"},{"com.yukista.tutaua.manager","Servei d’actualitzacions"}};
 @Override protected void onCreate(Bundle b){super.onCreate(b);immersive();LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(64),dp(32),dp(64),dp(28));page.setBackgroundColor(BG);TextView back=t("←  TORNAR",15,Color.WHITE,true);back.setFocusable(true);back.setClickable(true);back.setGravity(Gravity.CENTER);back.setBackground(panel(Color.rgb(31,38,55),Color.rgb(67,78,104),2));back.setOnClickListener(v->finish());page.addView(back,new LinearLayout.LayoutParams(dp(160),dp(44)));TextView title=t("Actualitzacions",34,Color.WHITE,true);LinearLayout.LayoutParams tl=new LinearLayout.LayoutParams(-1,-2);tl.topMargin=dp(16);page.addView(title,tl);page.addView(t("Versions instal·lades i canvis aplicats automàticament en aquest box.",16,MUTED,false));ScrollView scroll=new ScrollView(this);LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(0,dp(8),0,dp(10));scroll.addView(content);content.addView(section("APLICACIONS INSTAL·LADES"));LinearLayout apps=new LinearLayout(this);for(String[] a:APPS)apps.addView(app(a[0],a[1]),card());content.addView(apps);content.addView(section("HISTORIAL RECENT"));history(content);page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(page);back.requestFocus();}
 private View app(String pkg,String name){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(13),dp(10),dp(10));c.setBackground(panel(SURFACE,Color.rgb(50,61,84),1));c.addView(t(name,14,Color.WHITE,true));String version="No instal·lada";int color=Color.rgb(217,142,91);try{PackageInfo p=getPackageManager().getPackageInfo(pkg,0);version="Versió "+p.versionName+" · "+(android.os.Build.VERSION.SDK_INT>=28?p.getLongVersionCode():p.versionCode);color=Color.rgb(111,218,169);}catch(Exception ignored){}TextView s=t(version,12,color,false);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(8);c.addView(s,lp);return c;}
 private void history(LinearLayout out){try{JSONArray es=new JSONArray(getSharedPreferences(UpdateHistoryReceiver.PREFS,MODE_PRIVATE).getString(UpdateHistoryReceiver.KEY,"[]"));if(es.length()==0){out.addView(empty());return;}for(int i=0;i<es.length();i++){JSONObject e=es.getJSONObject(i);boolean ok=e.optBoolean("success");String n=name(e.optString("package")),v=e.optString("versionName"),when=new SimpleDateFormat("d MMM · HH:mm",new Locale("ca","ES")).format(new Date(e.optLong("time")));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(17),dp(11),dp(17),dp(11));row.setBackground(panel(SURFACE,ok?Color.rgb(42,83,72):Color.rgb(112,70,55),1));row.addView(t((ok?"✓  ":"!  ")+n+(v.isEmpty()?"":" · "+v),15,Color.WHITE,true));TextView detail=t((ok?"Instal·lada correctament":"No s’ha pogut instal·lar; es tornarà a provar")+" · "+when,12,MUTED,false);row.addView(detail);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.bottomMargin=dp(7);out.addView(row,rp);}}catch(Exception e){out.addView(empty());}}
 private TextView empty(){TextView v=t("Encara no hi ha actualitzacions registrades. Les següents apareixeran aquí automàticament.",15,MUTED,false);v.setPadding(dp(17),dp(16),dp(17),dp(16));v.setBackground(panel(SURFACE,Color.rgb(50,61,84),1));return v;}private TextView section(String s){TextView v=t(s,13,Color.rgb(150,128,255),true);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(17);p.bottomMargin=dp(8);v.setLayoutParams(p);return v;}private String name(String p){for(String[] a:APPS)if(a[0].equals(p))return a[1];return p;}private TextView t(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}private LinearLayout.LayoutParams card(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(96),1);p.setMargins(dp(4),0,dp(4),0);return p;}private GradientDrawable panel(int f,int s,int w){GradientDrawable d=new GradientDrawable();d.setColor(f);d.setCornerRadius(dp(14));d.setStroke(dp(w),s);return d;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private void immersive(){getWindow().getDecorView().setSystemUiVisibility(5894);}
}
